/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Can3D = (props) => {
  const group = useRef();
  const canGroup = useRef();
  const { nodes, materials, animations } = useGLTF("/assets/can1.glb");
  const { actions } = useAnimations(animations, group);

  useFrame((state, delta) => {
    const elapsedTime = state.clock.getElapsedTime();
    canGroup.current.rotation.y = elapsedTime * 2;
    canGroup.current.rotation.x = Math.sin(elapsedTime*2) * 0.1;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Can" position={[0, 0.2, 0]} ref={canGroup}>
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials["Can texture"]}
          />
          <mesh
            name="Cylinder_1"
            geometry={nodes.Cylinder_1.geometry}
            material={materials.CanMetal}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/assets/can1.glb");

export default Can3D;
